spring:
  application:
    name: monitor-sensors
  datasource:
    url: jdbc:postgresql://database-monitor:5432/postgres
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  issuer: SpringSecurityExample
  secret-key: FSmFQ0tNPt79eHKSiuaxu0Kwtie6El27XyVCPwTvlFU
  expiry-time-in-seconds: 86400